const SOURCE_STRATEGIES = {
  uniqueidentifier: 'uuid',
  nvarchar: 'text',
  nchar: 'text',
  varchar: 'text',
  char: 'text',
  text: 'text',
  ntext: 'text',
  xml: 'text',
  hierarchyid: 'text',
  geography: 'text',
  geometry: 'text',
  bit: 'boolean',
  tinyint: 'integer',
  smallint: 'integer',
  int: 'integer',
  bigint: 'bigint',
  decimal: 'numeric',
  numeric: 'numeric',
  money: 'numeric',
  smallmoney: 'numeric',
  float: 'double',
  real: 'real',
  date: 'date',
  datetime2: 'timestamp',
  datetime: 'timestamp',
  smalldatetime: 'timestamp',
  datetimeoffset: 'timestamptz',
  time: 'time',
  binary: 'bytea',
  varbinary: 'bytea',
  image: 'bytea',
};

const UNSUPPORTED = new Map([
  ['rowversion', 'SQL Server rowversion is generated by the engine and has no PostgreSQL equivalent'],
  ['timestamp_binary', 'SQL Server binary timestamp cannot be copied'],
  ['sql_variant', 'sql_variant values are not portable'],
]);

const LOSSY_TEXT_TYPES = new Set(['xml', 'hierarchyid', 'geography', 'geometry']);

const TARGET_CASTS = {
  uuid: 'uuid',
  text: 'text',
  boolean: 'boolean',
  integer: 'integer',
  bigint: 'bigint',
  numeric: 'numeric',
  double: 'double precision',
  real: 'real',
  date: 'date',
  timestamp: 'timestamp without time zone',
  timestamptz: 'timestamp with time zone',
  time: 'time',
  bytea: 'bytea',
  jsonb: 'jsonb',
  json: 'json',
  inet: 'inet',
  cidr: 'cidr',
};

const pad = (value, length = 2) => String(value).padStart(length, '0');

export const formatNaiveTimestamp = (value) => {
  if (value === null || value === undefined) return null;
  if (typeof value === 'string') return value;
  if (typeof value !== 'object' || typeof value.getFullYear !== 'function') return String(value);
  return (
    `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())} ` +
    `${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}.${pad(value.getMilliseconds(), 3)}`
  );
};

export const formatDate = (value) => {
  if (value === null || value === undefined) return null;
  if (typeof value === 'string') return value.slice(0, 10);
  if (typeof value !== 'object' || typeof value.getFullYear !== 'function') return String(value);
  return `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())}`;
};

export const formatTime = (value) => {
  if (value === null || value === undefined) return null;
  if (typeof value === 'string') return value;
  if (typeof value !== 'object' || typeof value.getHours !== 'function') return String(value);
  return `${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}`;
};

const STRATEGY_FORMATTERS = {
  timestamp: formatNaiveTimestamp,
  timestamptz: (value) => (value instanceof Date ? value.toISOString() : value),
  date: formatDate,
  time: formatTime,
  boolean: (value) => (typeof value === 'boolean' ? value : value === 1 || value === '1'),
  'json-text': (value) => {
    if (typeof value !== 'string') return value;
    const trimmed = value.trim();
    return trimmed ? trimmed : null;
  },
  'inet-array': (value) => {
    const entries = Array.isArray(value)
      ? value
      : typeof value === 'string'
        ? JSON.parse(value.trim() || '[]')
        : [];
    if (!Array.isArray(entries)) throw new Error('ip_whitelist is not a JSON array');
    return `{${entries.map((entry) => `"${String(entry).replace(/["\\]/g, '')}"`).join(',')}}`;
  },
};

export const toMigrationValue = (strategy, value) => {
  if (value === null || value === undefined) return null;
  const formatter = STRATEGY_FORMATTERS[strategy];
  if (formatter) return formatter(value);
  if (value instanceof Date) return value;
  if (Array.isArray(value)) return JSON.stringify(value);
  if (typeof value === 'object' && !Buffer.isBuffer(value)) return JSON.stringify(value);
  return value;
};

export const getSourceStrategy = (column) => {
  if (column.isComputed) return { strategy: 'skip', reason: 'computed column' };
  if (column.isRowVersion) return { strategy: 'skip', reason: 'rowversion column' };
  if (column.dataType === 'rowversion' || column.dataType === 'timestamp') {
    return { strategy: 'skip', reason: UNSUPPORTED.get('rowversion') };
  }
  if (column.dataType === 'sql_variant') {
    return { strategy: 'skip', reason: UNSUPPORTED.get('sql_variant') };
  }
  const strategy = SOURCE_STRATEGIES[column.dataType];
  if (!strategy) {
    return {
      strategy: 'skip',
      reason: `unsupported source type ${column.dataType}`,
    };
  }
  if (LOSSY_TEXT_TYPES.has(column.dataType)) {
    return {
      strategy,
      reason: `SQL Server ${column.dataType} is copied as text, verify the target column type`,
    };
  }
  return { strategy, reason: null };
};

export const getReadStrategy = (strategy) => (strategy === 'numeric' ? 'numeric-text' : 'native');

const ARRAY_ELEMENT_TYPES = new Set(['inet', 'cidr', 'text', 'varchar']);

const TEXT_TARGET_TYPES = new Set(['text', 'varchar', 'char', 'bpchar']);

export const getTargetCast = (targetColumn, strategy) => {
  if (!targetColumn) return { cast: null, valueStrategy: strategy, reason: null };

  const isArray = targetColumn.isArray || String(targetColumn.type || '').endsWith('[]');
  if (isArray) {
    const elementType = String(targetColumn.type).replace('[]', '');
    if (strategy === 'text' && ARRAY_ELEMENT_TYPES.has(elementType)) {
      return { cast: `${elementType}[]`, valueStrategy: 'inet-array', reason: null };
    }
    return { cast: null, valueStrategy: strategy, reason: 'target column is an array type' };
  }

  if (strategy === 'text' && ['jsonb', 'json'].includes(targetColumn.dataType)) {
    return { cast: TARGET_CASTS[targetColumn.dataType], valueStrategy: 'json-text', reason: null };
  }
  if (targetColumn.dataType === 'text' || TEXT_TARGET_TYPES.has(targetColumn.dataType)) {
    return { cast: null, valueStrategy: strategy, reason: null };
  }
  if (TARGET_CASTS[targetColumn.dataType]) {
    return { cast: TARGET_CASTS[targetColumn.dataType], valueStrategy: strategy, reason: null };
  }
  if (strategy === 'text') {
    return {
      cast: null,
      valueStrategy: strategy,
      reason: `SQL Server text copied into ${targetColumn.type}, add a cast if PostgreSQL cannot convert it`,
    };
  }
  return { cast: null, valueStrategy: strategy, reason: `no explicit cast for target type ${targetColumn.type}` };
};

export const isSafeTextToText = (sourceColumn, targetColumn) =>
  getSourceStrategy(sourceColumn).strategy === 'text' && targetColumn.dataType === 'text';

export { SOURCE_STRATEGIES, TARGET_CASTS, UNSUPPORTED };
