"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { FileText, Printer, ReceiptText, RefreshCw, ScrollText, Search } from "lucide-react";
import api from "@/lib/api";
import { formatCurrency, formatDate, toNumber } from "@/lib/format";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { EmptyState, ErrorState } from "@/components/ui/empty-state";
import { Panel, PanelBody, PanelHeader, PanelTitle } from "@/components/ui/panel";
import { Spinner } from "@/components/ui/spinner";
import { StatCard } from "@/components/ui/stat-card";
import { StatusBadge } from "@/components/ui/status-badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";

interface InvoiceRow {
  id: string;
  invoice_number: string;
  status?: string | null;
  invoice_date?: string | null;
  due_date?: string | null;
  total?: number | string;
  amount_paid?: number | string;
  customer_id?: string | null;
}

interface QuotationRow {
  id: string;
  quotation_number: string;
  customer_name?: string | null;
  status?: string | null;
  total?: number | string;
  valid_until?: string | null;
  created_at?: string | null;
}

interface ReceiptRow {
  id: string;
  sale_id: string;
  receipt_number?: string | null;
  invoice_number?: string | null;
  sale_date?: string | null;
  customer_name?: string | null;
  created_at?: string | null;
}

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "/api";

export default function DocumentsPage() {
  const [invoices, setInvoices] = useState<InvoiceRow[]>([]);
  const [quotations, setQuotations] = useState<QuotationRow[]>([]);
  const [receipts, setReceipts] = useState<ReceiptRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [query, setQuery] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    setError(false);
    try {
      const [invoiceList, quotationList, receiptList] = await Promise.all([
        api.invoices.getAll().catch(() => [] as InvoiceRow[]),
        api.quotations.getAll().catch(() => [] as QuotationRow[]),
        api.sales.getAllReceipts().catch(() => [] as ReceiptRow[]),
      ]);
      setInvoices(Array.isArray(invoiceList) ? invoiceList : []);
      setQuotations(Array.isArray(quotationList) ? quotationList : []);
      setReceipts(Array.isArray(receiptList) ? receiptList : []);
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const q = query.trim().toLowerCase();

  const filteredInvoices = useMemo(
    () =>
      invoices.filter((invoice) =>
        q ? invoice.invoice_number.toLowerCase().includes(q) : true
      ),
    [invoices, q]
  );
  const filteredQuotations = useMemo(
    () =>
      quotations.filter((quotation) =>
        q
          ? quotation.quotation_number.toLowerCase().includes(q) ||
            (quotation.customer_name ?? "").toLowerCase().includes(q)
          : true
      ),
    [quotations, q]
  );
  const filteredReceipts = useMemo(
    () =>
      receipts.filter((receipt) =>
        q
          ? String(receipt.receipt_number ?? "").toLowerCase().includes(q) ||
            String(receipt.invoice_number ?? "").toLowerCase().includes(q) ||
            (receipt.customer_name ?? "").toLowerCase().includes(q)
          : true
      ),
    [receipts, q]
  );

  const totals = useMemo(() => {
    const outstanding = invoices
      .filter((invoice) => invoice.status !== "paid")
      .reduce((sum, invoice) => sum + Math.max(0, (toNumber(invoice.total) ?? 0) - (toNumber(invoice.amount_paid) ?? 0)), 0);
    const quotationValue = quotations
      .filter((quotation) => quotation.status === "pending" || quotation.status === "sent")
      .reduce((sum, quotation) => sum + (toNumber(quotation.total) ?? 0), 0);
    return { outstanding, quotationValue };
  }, [invoices, quotations]);

  const isEmpty =
    invoices.length === 0 && quotations.length === 0 && receipts.length === 0;

  return (
    <div className="space-y-4">
      <PageHeader
        title="Documents"
        description="Receipts, invoices, and quotations generated by your business."
        actions={
          <>
            <Button variant="outline" size="sm" onClick={load} disabled={loading}>
              <RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} aria-hidden />
              Refresh
            </Button>
            <Button size="sm" asChild>
              <Link href="/dashboard/sales/new">
                <ReceiptText className="h-4 w-4" aria-hidden />
                New sale
              </Link>
            </Button>
          </>
        }
      />

      <div className="grid grid-cols-2 gap-2.5 lg:grid-cols-4">
        <StatCard label="Receipts" value={String(receipts.length)} icon={ReceiptText} />
        <StatCard label="Invoices" value={String(invoices.length)} icon={FileText} tone="info" />
        <StatCard
          label="Invoice outstanding"
          value={formatCurrency(totals.outstanding)}
          icon={FileText}
          tone="warning"
        />
        <StatCard
          label="Open quotations"
          value={formatCurrency(totals.quotationValue)}
          icon={ScrollText}
          tone="neutral"
        />
      </div>

      {error ? (
        <ErrorState title="Could not load documents" onRetry={load} retrying={loading} />
      ) : (
        <Tabs defaultValue="receipts">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <TabsList>
              <TabsTrigger value="receipts">Receipts ({receipts.length})</TabsTrigger>
              <TabsTrigger value="invoices">Invoices ({invoices.length})</TabsTrigger>
              <TabsTrigger value="quotations">Quotations ({quotations.length})</TabsTrigger>
            </TabsList>
            <div className="relative w-full sm:w-64">
              <Search
                className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"
                aria-hidden
              />
              <Input
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                placeholder="Search documents…"
                aria-label="Search documents"
                className="h-9 pl-9"
              />
            </div>
          </div>

          <TabsContent value="receipts">
            <Panel>
              <PanelHeader>
                <PanelTitle>Sale receipts</PanelTitle>
              </PanelHeader>
              <PanelBody className="p-0">
                {loading ? (
                  <div className="flex justify-center py-16">
                    <Spinner label="Loading receipts" />
                  </div>
                ) : filteredReceipts.length === 0 ? (
                  <EmptyState
                    icon={ReceiptText}
                    title={receipts.length === 0 ? "No receipts yet" : "No receipts match your search"}
                    description={receipts.length === 0 ? "Complete a sale to generate a receipt." : undefined}
                    className="m-4 border-0 bg-transparent"
                    action={
                      receipts.length === 0 ? (
                        <Button size="sm" asChild>
                          <Link href="/dashboard/sales/new">Open Point of Sale</Link>
                        </Button>
                      ) : undefined
                    }
                  />
                ) : (
                  <ul className="divide-y divide-border">
                    {filteredReceipts.map((receipt) => (
                      <li
                        key={receipt.id}
                        className="flex flex-col gap-2 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"
                      >
                        <div className="min-w-0">
                          <p className="truncate text-sm font-medium text-foreground">
                            {receipt.receipt_number || receipt.invoice_number || `Receipt ${receipt.id.slice(0, 8)}`}
                          </p>
                          <p className="mt-0.5 truncate text-xs text-muted-foreground">
                            {receipt.customer_name || "Walk-in customer"} · {formatDate(receipt.sale_date ?? receipt.created_at)}
                          </p>
                        </div>
                        <Button variant="outline" size="sm" asChild className="shrink-0">
                          <a
                            href={`${API_BASE}/sales/${receipt.sale_id}/receipt/html`}
                            target="_blank"
                            rel="noreferrer"
                          >
                            <Printer className="h-3.5 w-3.5" aria-hidden />
                            Open receipt
                          </a>
                        </Button>
                      </li>
                    ))}
                  </ul>
                )}
              </PanelBody>
            </Panel>
          </TabsContent>

          <TabsContent value="invoices">
            <Panel>
              <PanelHeader>
                <PanelTitle>Invoices</PanelTitle>
              </PanelHeader>
              <PanelBody className="p-0">
                {loading ? (
                  <div className="flex justify-center py-16">
                    <Spinner label="Loading invoices" />
                  </div>
                ) : filteredInvoices.length === 0 ? (
                  <EmptyState
                    icon={FileText}
                    title={invoices.length === 0 ? "No invoices yet" : "No invoices match your search"}
                    className="m-4 border-0 bg-transparent"
                  />
                ) : (
                  <ul className="divide-y divide-border">
                    {filteredInvoices.map((invoice) => {
                      const balance = Math.max(
                        0,
                        (toNumber(invoice.total) ?? 0) - (toNumber(invoice.amount_paid) ?? 0)
                      );
                      return (
                        <li
                          key={invoice.id}
                          className="flex flex-col gap-2 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"
                        >
                          <div className="min-w-0">
                            <div className="flex flex-wrap items-center gap-2">
                              <p className="truncate text-sm font-medium text-foreground">
                                {invoice.invoice_number}
                              </p>
                              <StatusBadge status={invoice.status} />
                            </div>
                            <p className="mt-0.5 text-xs text-muted-foreground">
                              {formatDate(invoice.invoice_date)}
                              {invoice.due_date ? ` · due ${formatDate(invoice.due_date)}` : ""}
                              {balance > 0 ? ` · ${formatCurrency(balance)} outstanding` : ""}
                            </p>
                          </div>
                          <span className="shrink-0 text-sm font-semibold tabular-nums text-foreground">
                            {formatCurrency(invoice.total)}
                          </span>
                        </li>
                      );
                    })}
                  </ul>
                )}
              </PanelBody>
            </Panel>
          </TabsContent>

          <TabsContent value="quotations">
            <Panel>
              <PanelHeader>
                <PanelTitle>Quotations</PanelTitle>
              </PanelHeader>
              <PanelBody className="p-0">
                {loading ? (
                  <div className="flex justify-center py-16">
                    <Spinner label="Loading quotations" />
                  </div>
                ) : filteredQuotations.length === 0 ? (
                  <EmptyState
                    icon={ScrollText}
                    title={quotations.length === 0 ? "No quotations yet" : "No quotations match your search"}
                    className="m-4 border-0 bg-transparent"
                  />
                ) : (
                  <ul className="divide-y divide-border">
                    {filteredQuotations.map((quotation) => (
                      <li
                        key={quotation.id}
                        className="flex flex-col gap-2 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"
                      >
                        <div className="min-w-0">
                          <div className="flex flex-wrap items-center gap-2">
                            <p className="truncate text-sm font-medium text-foreground">
                              {quotation.quotation_number}
                            </p>
                            <StatusBadge status={quotation.status} />
                          </div>
                          <p className="mt-0.5 text-xs text-muted-foreground">
                            {quotation.customer_name || "No customer"}
                            {quotation.valid_until ? ` · valid until ${formatDate(quotation.valid_until)}` : ""}
                          </p>
                        </div>
                        <span className="shrink-0 text-sm font-semibold tabular-nums text-foreground">
                          {formatCurrency(quotation.total)}
                        </span>
                      </li>
                    ))}
                  </ul>
                )}
              </PanelBody>
            </Panel>
          </TabsContent>
        </Tabs>
      )}

      {!loading && !error && isEmpty ? (
        <p className="text-center text-xs text-muted-foreground">
          Documents appear here automatically as you record sales, invoices, and quotations.
        </p>
      ) : null}
    </div>
  );
}
